services:
  api-proxy:
    image: ${IMAGE_TAG}
    build:
      context: .
    volumes:
      - ./ssh:/ssh:ro
      - ./remote_command:/remote_command:ro
    ports:
      - "${LOCAL_PORT}:80"
    env_file:
      - .env
    restart: always
